workflows:
  react-native-android:
    name: Build React Native Android APK
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.amuthamorderapp"   # change this to your app ID
      node: 18
      npm: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
