workflows:
  react-native-apk:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 18
      node: $NODE_VERSION
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Fix gradlew permissions
        script: |
          chmod +x android/gradlew
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
